# .streamlit/secrets.toml

public_gsheets_url = "https://docs.google.com/spreadsheets/d/1BLhMOU0EzyoThPcIUnVBMuCtaNtAe8qrWlFPiPSjEY8/edit?usp=sharing"

gs_url = "https://docs.google.com/spreadsheets/d/1QdERm1e8tpZoJ7Na-9zyvhP84-x1MGzZaMWPnEEa_04/edit#gid=1095929062"
